services:
  broker:
    image: confluentinc/cp-kafka:8.2.0
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093' # Format: nodeID@hostname:port
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_LISTENERS: 'PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    # Give time for Kafka to boot up by performing healthcheck
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "broker:29092"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  matches-events-producer:
    build: 
      context: .
      dockerfile: producers/Dockerfile
    container_name: matches-events-producer
    depends_on:
      broker:
        condition: service_healthy
    env_file:
      - .env
    environment:
      PRODUCER_TYPE: matches_events

  standings-producer:
    build:
      context: .
      dockerfile: producers/Dockerfile
    container_name: standings-producer
    depends_on:
      broker:
        condition: service_healthy
    env_file:
      - .env
    environment:
      PRODUCER_TYPE: standings
  
  consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    container_name: consumer
    depends_on:
      broker:
        condition: service_healthy
    env_file:
      - .env

  dbt:
    build:
      context: .
      dockerfile: dbt_project/Dockerfile
    container_name: dbt
    depends_on:
      broker:
        condition: service_healthy
    env_file:
      - .env

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: michelin-snowflake-datasource
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/plugins:/var/lib/grafana/plugins
    depends_on:
      broker:
        condition: service_healthy
  
  # Adding Streamlit adpp, as Grafana does not give all that I would like in terms of UI
  streamlit:
    build:
      context: .
      dockerfile: streamlit_app/Dockerfile
    container_name: streamlit
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      broker:
        condition: service_healthy