wc2026:
  target: dev # Only using one environment
  outputs:
    dev:
      type: snowflake
      organization_name: "{{ env_var('SNOWFLAKE_ORGANIZATION') }}"
      account_name: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_DBT_ROLE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      schema: "{{ env_var('SNOWFLAKE_ANALYTICS_SCHEMA') }}"
      threads: 4