{{
    config(
        materialized='incremental',
        unique_key='TEAM_ID'
    )
}}

WITH matches AS (
    SELECT * FROM {{ ref('stg_matches') }}
),

finished_matches AS(
    SELECT *
    FROM matches
    WHERE STATUS = 'FINISHED'
),

home_stats AS (
    SELECT
        HOME_TEAM AS TEAM_NAME,
        COUNT(*) AS HOME_GAMES,
        SUM(CASE WHEN HOME_SCORE > AWAY_SCORE THEN 1 ELSE 0 END) AS HOME_WINS,
        SUM(CASE WHEN HOME_SCORE = AWAY_SCORE THEN 1 ELSE 0 END) AS HOME_DRAWS,
        SUM(CASE WHEN HOME_SCORE < AWAY_SCORE THEN 1 ELSE 0 END) AS HOME_LOSSES,
        SUM(HOME_SCORE) AS HOME_GOALS_SCORED,
        SUM(AWAY_SCORE) AS HOME_GOALS_CONCEDED,
        SUM(CASE WHEN AWAY_SCORE = 0 THEN 1 ELSE 0 END) AS HOME_CLEAN_SHEETS
    FROM finished_matches
    GROUP BY HOME_TEAM
),

away_stats AS (
    SELECT
        AWAY_TEAM AS TEAM_NAME,
        COUNT(*) AS AWAY_GAMES,
        SUM(CASE WHEN AWAY_SCORE > HOME_SCORE THEN 1 ELSE 0 END) AS AWAY_WINS,
        SUM(CASE WHEN AWAY_SCORE = HOME_SCORE THEN 1 ELSE 0 END) AS AWAY_DRAWS,
        SUM(CASE WHEN AWAY_SCORE < HOME_SCORE THEN 1 ELSE 0 END) AS AWAY_LOSSES,
        SUM(AWAY_SCORE) AS AWAY_GOALS_SCORED,
        SUM(HOME_SCORE) AS AWAY_GOALS_CONCEDED,
        SUM(CASE WHEN HOME_SCORE = 0 THEN 1 ELSE 0 END) AS AWAY_CLEAN_SHEETS
    FROM finished_matches
    GROUP BY AWAY_TEAM
),

combined AS (
    SELECT
        COALESCE(h.TEAM_NAME, a.TEAM_NAME) AS TEAM_NAME,
        COALESCE(h.HOME_GAMES, 0) + COALESCE(a.AWAY_GAMES, 0) AS TOTAL_GAMES,
        COALESCE(h.HOME_WINS, 0) + COALESCE(a.AWAY_WINS, 0) AS TOTAL_WINS,
        COALESCE(h.HOME_DRAWS, 0) + COALESCE(a.AWAY_DRAWS, 0) AS TOTAL_DRAWS,
        COALESCE(h.HOME_LOSSES, 0) + COALESCE(a.AWAY_LOSSES, 0) AS TOTAL_LOSSES,
        COALESCE(h.HOME_GOALS_SCORED, 0) + COALESCE(a.AWAY_GOALS_SCORED, 0) AS TOTAL_GOALS_SCORED,
        COALESCE(h.HOME_GOALS_CONCEDED, 0) + COALESCE(a.AWAY_GOALS_CONCEDED, 0) AS TOTAL_GOALS_CONCEDED,
        COALESCE(h.HOME_CLEAN_SHEETS, 0) + COALESCE(a.AWAY_CLEAN_SHEETS, 0) AS TOTAL_CLEAN_SHEETS
    FROM home_stats h
    FULL OUTER JOIN away_stats a
        ON h.TEAM_NAME = a.TEAM_NAME
),

joined_to_teams AS (
    SELECT
        t.TEAM_ID,
        c.TEAM_NAME,
        t.FLAG,
        t.COUNTRY_CODE,
        t.CONFEDERATION,
        c.TOTAL_GAMES,
        c.TOTAL_WINS,
        c.TOTAL_DRAWS,
        c.TOTAL_LOSSES,
        c.TOTAL_GOALS_SCORED,
        c.TOTAL_GOALS_CONCEDED,
        c.TOTAL_CLEAN_SHEETS,
        ROUND(c.TOTAL_WINS / NULLIF(c.TOTAL_GAMES, 0) * 100, 1) AS WIN_PERCENTAGE,
        ROUND(c.TOTAL_GOALS_SCORED / NULLIF(c.TOTAL_GAMES, 0), 2) AS GOALS_PER_GAME,
        ROUND(c.TOTAL_GOALS_CONCEDED / NULLIF(c.TOTAL_GAMES, 0), 2) AS GOALS_CONCEDED_PER_GAME
    FROM combined c
    LEFT JOIN {{ ref('teams') }} t
        ON c.TEAM_NAME = t.TEAM_NAME
),

final AS (
    SELECT *
    FROM joined_to_teams
    {% if is_incremental() %}
    WHERE TEAM_ID NOT IN (SELECT TEAM_ID FROM {{ this }})
        OR TOTAL_GAMES > (
            SELECT TOTAL_GAMES
            FROM {{ this }} existing
            WHERE existing.TEAM_ID = joined_to_teams.TEAM_ID
        )
    {% endif %}
)

SELECT * FROM final
ORDER BY WIN_PERCENTAGE DESC, TOTAL_GOALS_SCORED DESC